name = "Best Modpack"
author = "chyzman"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb2e22cbb415139764a2f0e02732da4d6bcd6a57c6596eda4052299c16dc3f1d"

[versions]
fabric = "0.18.0"
minecraft = "1.21.1"
