name = "Best Modpack"
author = "chyzman"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2633c1b7083b22f861e066303d253ac069056b174f006150631a4c5147d565e3"

[versions]
fabric = "0.18.0"
minecraft = "1.21.1"
