name = "Best Modpack"
author = "chyzman"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc8a1c22dc5dd7374ae1ca632238ad6579d547ce497791813dbd79520c687a03"

[versions]
fabric = "0.18.0"
minecraft = "1.21.1"
