name = "Best Modpack"
author = "chyzman"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49a96c16a301603f5c53a6bf30d5db62effccca75d47d440ed9fcf7a0b530f57"

[versions]
fabric = "0.18.0"
minecraft = "1.21.1"
