name = "Best Modpack"
author = "chyzman"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a3cd572f8ee955053a0b166c86ba0fa2523a78eda925de6489f8a0d3af4a598"

[versions]
fabric = "0.18.0"
minecraft = "1.21.1"
