name = "Best Modpack"
author = "chyzman"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2b84cc5bf3750d393c3a07f9300127dca1d07060810eae2095b43dd7f5e4dfe"

[versions]
fabric = "0.18.0"
minecraft = "1.21.1"
