name = "Best Modpack"
author = "chyzman"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2cf31049ec04200a5c7b344da7552726520644ffe6667f6d4826ca3777847fbc"

[versions]
fabric = "0.18.0"
minecraft = "1.21.1"
