[Server]
	#Swim speed multiplier
	# Default: 1.5
	# Range: 1.0 ~ 10.0
	swimSpeedMultiplier = 3.0
	#Water breathing
	waterBreathing = true
	#Night vision
	nightVision = true
	#Aqua affinity (underwater mining speed)
	aquaAffinity = true
