enabled = true
sendServerConfig = true
sendDistance = true
maxDistance = 0
directionPrecision = 300.0
ticksBetweenUpdates = 5
sneakingHides = true
pumpkinHides = true
mobHeadsHide = true
invisibilityHides = true
visible = true
visibleEmpty = false
acceptServerConfig = true
fadeMarkers = true
fadeStart = 100
fadeEnd = 1000
fadeEndOpacity = 0.30000001192092896
showHeight = true
alwaysShowHeads = true
showHeadsOnTab = true
showNamesOnTab = false
colorMode = "UUID"
constantColor = 0xffffff